version: "3"
services:
  springbootapp:
    build: ./
    container_name: momo_app
    ports:
      - 8080:8080
    depends_on:
      - momo_redis
      - momo_mysql
    networks:
      - springboot-net
    links:
      - momo_mysql 

  momo_mysql:
    image: mysql

    container_name: momo_mysql
    environment:
      MYSQL_DATABASE: momo_test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD : test
    ports:
       - 3306:3306
    networks:
      - springboot-net   

  momo_redis:
    image: redis
    container_name: momo_redis

    ports:
      - 6379:6379
    networks:
      - springboot-net   

networks:
  springboot-net:
         driver: bridge