server:
  port: 8080
  servlet:
    context-path: /

spring:
  profiles:
    # active: aws
    active: prod

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jackson:
    default-property-inclusion: non_null